/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 mushrooms.gltf
Author: leha_pu (https://sketchfab.com/leha_pu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mushrooms-f9dbd4c34a4f4389bf3901527ecc89a0
Title: Mushrooms
*/

import { useGLTF } from '@react-three/drei'
// import { useStore } from '../hooks/useStore'

export function Mushrooms(props) {

  let number = Math.floor(Math.random() * (8 - 2) + 2)
	// const [removeCube] = useStore((state) => [state.addCube])
  let none = true

  const { nodes, materials } = useGLTF('/mushrooms.gltf')
  return (
    <group {...props} dispose={null}
    className={none ? 'none' : ''}

    style={{  display: 'none'}}
    onClick={(e) => {
      none = !none
      e.stopPropagation()

      console.log(this)
      console.log(e.target)
      // className.add('none')
      // const [x, y, z] = Object.values(e.point).map(val => Math.ceil(val));
      // removeCube(x, y, z)
    }}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.2} position={props.position}>
        <mesh
            style={{  display: 'none'}}

        geometry={nodes[`Object_${number}`].geometry} material={materials[`Mushrooms${number}`]} />

        {/* <mesh geometry={nodes.Object_3.geometry} material={materials.Mushrooms3} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Mushrooms4} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Mushrooms5} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Mushrooms6} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Mushrooms7} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Mushrooms1} /> */}
      </group>
    </group>
  )
}

useGLTF.preload('/mushrooms.gltf')
