/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 mushrooms.gltf
Author: leha_pu (https://sketchfab.com/leha_pu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mushrooms-f9dbd4c34a4f4389bf3901527ecc89a0
Title: Mushrooms
*/

import { useGLTF } from '@react-three/drei'
// import { useStore } from '../hooks/useStore'

export function Mushrooms(props) {

  // let number = Math.floor(Math.random() * (8 - 2) + 2)
	// const [removeCube] = useStore((state) => [state.addCube])
  let none = true

  const { nodes, materials } = useGLTF('/mushrooms.gltf')
  return (
    <group {...props} dispose={null}
    className={none ? 'none' : ''}

    style={{  display: 'none'}}
    onClick={() => props.handleDeleteMush(props.arr)}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.2} position={props.position}>
        <mesh
            style={{  display: 'none'}}

        geometry={nodes[`Object_${props.number}`].geometry} material={materials[`Mushrooms${props.number}`]} />
      </group>
    </group>
  )
}

useGLTF.preload('/mushrooms.gltf')
